name: test workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building project..."

  notify-msg:
    needs: build
    if: always()
    uses: nikhilande/shared_call-test/.github/workflows/resuableTemp.yaml@main
    with:
      repository: ${{ github.repository }}
      workflow: ${{ github.workflow }}
      status: ${{ needs.build.result }}
      branch: ${{ github.ref_name }}
      run_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets:
      TEAMS_FLOW_URL: ${{ secrets.TEAMS_FLOW_URL }}